add wave -noupdate -divider {altera_nios2_qsys_wwesmo5z: top-level ports}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/i_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/i_readdatavalid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/i_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/i_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/i_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/d_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/d_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/d_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/d_byteenable
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/d_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/d_write
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/d_writedata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/d_irq
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/d_readdatavalid
add wave -noupdate -divider {altera_nios2_qsys_wwesmo5z: base pipeline}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/F_pcb_nxt
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/F_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/E_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/M_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/W_pcb
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/F_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/E_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/M_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/W_vinst
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/F_inst_ram_hit
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/F_iw_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/F_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/F_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_refetch
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_rdprs_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_rdprs_stall_done
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/E_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/M_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/W_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/W_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/W_dst_regnum
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/W_wr_data
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/E_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/M_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/F_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/D_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/E_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/M_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/M_pipe_flush_baddr
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/norm_intr_req
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_status_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_status_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_estatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_estatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_bstatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_bstatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ienable_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ienable_reg_irq0
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ienable_reg_irq1
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ienable_reg_irq2
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ienable_reg_irq3
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ienable_reg_irq4
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ienable_reg_irq5
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ienable_reg_irq6
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ienable_reg_irq7
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ipending_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ipending_reg_irq0
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ipending_reg_irq1
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ipending_reg_irq2
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ipending_reg_irq3
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ipending_reg_irq4
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ipending_reg_irq5
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ipending_reg_irq6
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_ipending_reg_irq7
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/A_cpuid_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_wwesmo5z/E_valid_prior_to_hbreak

configure wave -justifyvalue right
configure wave -signalnamewidth 1
TreeUpdate [SetDefaultTree]
